
//Production
GET https://cse341-schoolassignment.onrender.com/contacts HTTP/1.1
###
GET https://cse341-schoolassignment.onrender.com/contacts/664a7d19b30af4fb0cdd85a5 HTTP/1.1


//LocalHost
###
GET http://localhost:8080/contacts HTTP/1.1
###
GET http://localhost:8080/contacts/664a7d19b30af4fb0cdd85a5 HTTP/1.1